controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

velocity_controller:
  ros__parameters:
    joints:
      - wheel_front_left_joint
      - wheel_front_right_joint
      - wheel_rear_left_joint
      - wheel_rear_right_joint