import os
from ament_index_python.packages import get_package_share_directory

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node

def generate_launch_description():
    # 1. Get the path to the package directory to locate the params file
    waregv_navigation_dir = get_package_share_directory("waregv_navigation")
    
    # 2. Setup Launch Configurations
    use_sim_time = LaunchConfiguration('use_sim_time')
    params_file = LaunchConfiguration('params_file')
    
    # 3. Declare Launch Arguments
    use_sim_time_arg = DeclareLaunchArgument(
        name="use_sim_time", 
        default_value='false',
        description='Use simulation (Gazebo) clock if true'
    )
    
    params_file_arg = DeclareLaunchArgument(
        name='params_file',
        default_value=os.path.join(waregv_navigation_dir, 'config', 'nav2_params.yaml'),
        description='Full path to the ROS2 parameters file to use for all Nav2 nodes'
    )

    # 4. Define the Lifecycle Nodes required for basic Navigation
    # We define a list of node names so we can easily pass them to the lifecycle manager later.
    lifecycle_nodes = ['controller_server',
                       'planner_server',
                       'behavior_server',
                       'bt_navigator']

    # Node A: Controller Server
    # Responsible for local navigation (following the path generated by the planner, avoiding local obstacles).
    # It outputs velocity commands (cmd_vel) to the robot.
    controller_server = Node(
        package='nav2_controller',
        executable='controller_server',
        name='controller_server',
        output='screen',
        parameters=[params_file, {'use_sim_time': use_sim_time}]
    )

    # Node B: Planner Server
    # Responsible for global navigation (computing the shortest/best path from A to B).
    # It uses the global costmap (provided dynamically by SLAM) to find a valid route.
    planner_server = Node(
        package='nav2_planner',
        executable='planner_server',
        name='planner_server',
        output='screen',
        parameters=[params_file, {'use_sim_time': use_sim_time}]
    )

    # Node C: Behavior Server (formerly recoveries_server in older ROS2 distros)
    # Handles recovery behaviors if the robot gets stuck (e.g., spinning in place, backing up, clearing costmaps).
    behavior_server = Node(
        package='nav2_behaviors',
        executable='behavior_server',
        name='behavior_server',
        output='screen',
        parameters=[params_file, {'use_sim_time': use_sim_time}]
    )

    # Node D: Behavior Tree Navigator
    # The "brain" of Nav2. It takes your goal pose and runs an XML-based behavior tree
    # to coordinate the Planner, Controller, and Behaviors servers.
    bt_navigator = Node(
        package='nav2_bt_navigator',
        executable='bt_navigator',
        name='bt_navigator',
        output='screen',
        parameters=[params_file, {'use_sim_time': use_sim_time}]
    )

    # 5. Define the Lifecycle Manager Node
    # Takes the list of `lifecycle_nodes` defined above and transitions them 
    # through the Unconfigured -> Inactive -> Active states in the correct order.
    lifecycle_manager = Node(
        package='nav2_lifecycle_manager',
        executable='lifecycle_manager',
        name='lifecycle_manager_navigation',
        output='screen',
        parameters=[
            {'use_sim_time': use_sim_time},
            {'autostart': True},
            {'node_names': lifecycle_nodes}
        ]
    )

    # 6. Return the LaunchDescription object
    return LaunchDescription([
        use_sim_time_arg,
        params_file_arg,
        controller_server,
        planner_server,
        behavior_server,
        bt_navigator,
        lifecycle_manager
    ])